# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Сообщество Elixir и Phoenix Framework
email: elixir@wunsh.ru
description: >
  Русскоязычное сообщество Elixir и Phoenix Framework
baseurl: ""
url: "https://wunsh.ru"

lang: "ru"

# Build settings
markdown: kramdown
theme: wunsh-theme

name: Эликсир и&nbsp;Вунш
tagline: Erlang + Ruby = &#10084;
home_title: Вунш&nbsp;&mdash; русскоязычное сообщество разработчиков на&nbsp;языке программирования Elixir и&nbsp;Phoenix Framework.

gems:
  - jekyll-feed
  - jekyll-archives
  - jekyll-paginate
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor

permalink: none

timezone: "Europe/Moscow"

# Build settings

verifications:
  yandex-verification: 0e259c9bb6d411cb

paginate: 8
paginate_path: "/pages/:num/"

permalink: /:categories/:title.html

defaults:
  -
    scope:
      path: "articles"
    values:
      layout: post
      permalink: /:categories/:title.html
  -
    scope:
      path: "news"
    values:
      layout: post
      permalink: /:categories/:year/:title.html

authors:
  jaroslav:
    name: Ярослав
    gender: male
  nadezhda:
    name: Надежда Нестерова
    gender: female
