version: "3"

services:
  web:
    restart: always
    image: nginx:1.15-alpine
    container_name: wunsh-web
    env_file:
      - .env
    volumes:
      - /etc/nginx/conf.d/wunsh.ru
      - /etc/nginx/conf.d
      - /etc/nginx/vhost.d
      - ./_site:/usr/share/nginx/html

  app:
    image: jekyll/minimal:3.8
    container_name: wunsh-app
    command: jekyll server
    env_file:
      - .env
    volumes:
      - .:/srv/jekyll
      - ./vendor/bundle:/usr/local/bundle
    ports:
      - 4000:4000
      - 35729:35729

  builder:
    image: jekyll/builder:3.8
    container_name: wunsh-builder
    command: jekyll build
    env_file:
      - .env
    volumes:
      - .:/srv/jekyll
      - ./vendor/bundle:/usr/local/bundle


networks:
  default:
    external:
      name: nginx-proxy
